# Generated by Django 3.0.6 on 2021-07-05 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('environment_monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='humidity',
            name='device_name',
            field=models.CharField(default='iot_ms', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='device_name',
            field=models.CharField(default='iot_ms', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='humidity',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='temperature',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
