# Generated by Django 3.0.6 on 2021-07-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment_monitor', '0002_auto_20210704_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=10)),
                ('sent_frequency', models.IntegerField()),
            ],
            options={
                'db_table': 'device',
            },
        ),
    ]
