# Generated by Django 3.0.6 on 2021-04-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoundRecorded',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('amplitude', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
