# Generated by Django 3.0.6 on 2021-05-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sound_recorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundrecorded',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
