# Generated by Django 3.2.9 on 2022-06-21 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SdInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_storage', models.IntegerField()),
                ('free_storage', models.IntegerField()),
                ('used_storage', models.IntegerField()),
            ],
            options={
                'db_table': 'sd_info',
            },
        ),
    ]
