# Generated by Django 3.2.9 on 2022-06-21 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniM5Stack', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='sdinfo',
            name='device_name',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
