# Generated by Django 3.2.9 on 2022-06-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AniM5Stack', '0002_auto_20220620_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdinfo',
            name='free_storage',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sdinfo',
            name='total_storage',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sdinfo',
            name='used_storage',
            field=models.BigIntegerField(),
        ),
    ]
